name: sec-checks
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  trivy-file-system:
    name: Trivy Scan
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: json
          output: ./results.json
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: "1"
      - name: Inspect action report
        if: always()
        run: cat ./results.json
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: ./results.json
  trivy-sarif:
    name: Trivy Sarif Scan
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: ./results.sarif
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: "1"
      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: './results.sarif'
  grype-file-system:
    name: Grype Scan
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Grype vulnerability scanner in repo mode
        uses: anchore/scan-action@v3
        with:
          path: "."
          output-format: json
          severity-cutoff: medium
          fail-build: true
      - name: Inspect action report
        if: always()
        run: cat ./results.json
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-scan-results
          path: ./results.json
  grype-sarif:
    name: Grype Sarif Scan
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Grype vulnerability scanner in repo mode
        uses: anchore/scan-action@v3
        with:
          path: "."
          output-format: sarif
          severity-cutoff: medium
          fail-build: true
      - name: Upload Grype scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: './results.sarif'