name: sec-checks
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  trivy-file-system:
    name: Trivy Scan
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: json
          output: ./trivy-results.json
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: "1"
      - name: Inspect action report
        if: always()
        run: cat ./trivy-results.json
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: trivy code report
          path: ./trivy-results.json
  grype-file-system:
    name: Grype Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Grype vulnerability scanner in repo mode
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: true
          severity-cutoff: medium
          output-format: json
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ./results.sarif
      - name: upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: grype-scan-results
          path: ./results.json
      - name: Inspect action SARIF report
        if: always()
        run: cat ./results.json